<a href="https://colab.research.google.com/github/amitk9605-code/masai/blob/main/NumPy_Power_Tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
l = range(1000000)

In [ ]:
%timeit [i ** 2 for i in l]

92 ms ± 1.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
import numpy as np

l = np.array(range(1000000))

In [ ]:
%timeit l ** 2

1.07 ms ± 139 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
arr1 = np.array(range(10))
arr1.ndim

1

In [ ]:
arr1.shape

(10,)

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [10, 11, 12]])
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr3 = np.array([[1, 2, 3,10], [4, 5, 6,11], [10, 11, 12,13]])
print(arr3)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [10 11 12 13]]


In [ ]:
arr3.ndim

2

In [ ]:
arr3.shape

(3, 4)

In [ ]:
a = np.arange(1,5,2)
a

array([1, 3])

In [ ]:
arr3 = np.arange(1, 5, 0.5)
arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[0]

np.int64(0)

In [ ]:
m1[-11]

np.int64(1)

In [ ]:
m1[-1]

np.int64(11)

In [ ]:
m1[[2,3,4,1,2,2]]

array([2, 3, 4, 1, 2, 2])

In [ ]:
m1 = np.array([100,200,300,400,500,600])
m1

array([100, 200, 300, 400, 500, 600])

In [ ]:
m1[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

In [ ]:
m1[2,3,4,1,2,2]

IndexError: too many indices for array: array is 1-dimensional, but 6 were indexed

In [ ]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m1[:5]

array([1, 2, 3, 4, 5])

In [ ]:
m1[-5:-1]

array([6, 7, 8, 9])

In [ ]:
m1[-5: -1: -1]

array([], dtype=int64)

In [ ]:
#Fancy Indexing

arr = np.array([10, 20, 30, 40, 50])
print(arr[[0,2,4]])

[10 30 50]


In [ ]:
arr = np.array([100, 200, 300, 400, 500])
indices = [3, 1, 4, 0]
print(arr[indices])

[400 200 500 100]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print(mask)

[False False  True  True  True]


In [ ]:
print(arr[mask])

[30 40 50]


In [ ]:
#Ufuncs

arr = np.array([1, 2, 3, 4, 5])

print(np.add(arr, 5))
print(np.square(arr))
print(np.sqrt(arr))
print(np.exp(arr))

[ 6  7  8  9 10]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3,4])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
#Ufuncs with Broadcasting

arr = np.array([1, 2, 3])
print(np.add(arr,10))

[11 12 13]
